# Generated by Django 3.2.8 on 2022-08-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_wallet_client_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='img',
            field=models.ImageField(default='photo.jpg', upload_to='Logo'),
        ),
    ]
