# Generated by Django 3.2.8 on 2022-08-28 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_alter_study_name_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_private', models.CharField(max_length=150)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.study')),
            ],
        ),
    ]
