# Generated by Django 3.2.8 on 2022-08-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='n_transaction',
            field=models.CharField(default='AD000000000000001', max_length=150),
        ),
    ]
