# Generated by Django 3.2.8 on 2022-08-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_wallet_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
